name: Delete Releases

on:
  schedule:
    # Runs at 3:00 AM UTC every Sunday
    - cron: '0 3 * * 0'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old releases and tags
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          releases_keep_latest: 5
          delete_tags: true
          gh_token: ${{ secrets.GITHUB_TOKEN }}