name: Android CI with Maven
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Install Appium
        run:  |
          npm i -g appium
          appium --version
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven- 
    
      - name: Restart ADB Server
        run: |
          adb kill-server || true # Ignore if ADB is not running
          adb start-server
      
      - name: List Available System Images
        run: sdkmanager --list

      # Step 8: Install Required System Image if not already installed
      - name: Install Required System Image
        run: sdkmanager "system-images;android-29;default;x86_64"

      - name: Install Emulator and Tools
        run: |
          sdkmanager "emulator" "platform-tools" "platforms;android-29" "system-images;android-29;default;x86_64"
  
      - name: Create AVDs
        run: |
          echo "Creating first AVD..."
          echo "no" | avdmanager create avd -n emulator1 -k "system-images;android-29;default;x86_64" --force --abi default/x86_64 --device "pixel"
          echo "Creating second AVD..."
          echo "no" | avdmanager create avd -n emulator2 -k "system-images;android-29;default;x86_64" --force --abi default/x86_64 --device "pixel"
          echo "Starting first emulator..."
          sleep 120
          emulator -avd emulator1 -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim &
          echo "Starting second emulator..."
          emulator -avd emulator2 -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim &
          echo "Emulator started - checking devices:"
          timeout 180 bash -c '
            while ! adb devices | grep -q "emulator-5554"; do
              echo "Waiting for emulator to connect..."
              sleep 5
            done
          '
          adb devices -l
          echo " Both Emulators are ready"
          echo "Starting Appium Server....."
          appium & sleep 5
          echo "Running Tests on apk"
          mvn test
