name: Android CI with Maven
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          

          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Appium
        run:  |
          npm i -g appium
          appium --version
        
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven- 
    
      - name: Prepare ADB and SDK
        run: |
          echo "$HOME/Library/Android/sdk/emulator" >> $GITHUB_PATH
          echo "$HOME/Library/Android/sdk/platform-tools" >> $GITHUB_PATH
          adb kill-server
          adb start-server
      
      - name: Install Android Components
        run: |
          sdkmanager --install "platforms;android-29" "system-images;android-29;default;x86_64"
          sdkmanager --install "emulator" "platform-tools"
          yes | sdkmanager --licenses

      - name: Create AVD
        run: |
          avdmanager create avd \
            -n test_emulator \
            -k "system-images;android-29;default;x86_64" \
            --device "pixel_4" \
            --force

      - name: Start Emulator
        run: |
          $ANDROID_SDK_ROOT/emulator/emulator \
            -avd test_emulator \
            -no-window \
            -no-audio \
            -no-boot-anim \
            -gpu swiftshader_indirect &

          # Wait for emulator to boot
          timeout 180 bash -c '
            while ! adb devices | grep -q "emulator-5554"; do
              echo "Waiting for emulator to connect..."
              sleep 5
            done
          '

          # Verify devices
          adb devices -l
          adb shell getprop sys.boot_completed

      - name: Start Appium Server
        run: |
          appium --port 4723 &
          sleep 10  # Give Appium time to start

      - name: Run Tests
        run: mvn clean test -Dappium.port=4723
