name: Android CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13
    steps:
      # Step 1: Checkout the code from the repository
      - uses: actions/checkout@v4
      
      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      # Step 3: Install Appium
      - name: Install Appium
        run: |
          npm install -g appium
          appium --version
          
      # Step 4: Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      # Step 5: Cache Maven packages
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
    
      # Step 6: Restart ADB Server
      - name: Restart ADB Server
        run: |
          adb kill-server || true # Ignore if ADB is not running
      
      # Step 7: List Available System Images (for debugging)
      - name: List Available System Images
        run: sdkmanager --list

      # Step 8: Install Required System Image if not already installed
      - name: Install Required System Image
        run: sdkmanager "system-images;android-29;default;x86_64"

      # Step 9: Install Emulator and Tools
      - name: Install Emulator and Tools
        run: |
          sdkmanager "emulator" "platform-tools" "platforms;android-29" "system-images;android-29;default;x86_64"
  
      # Step 10: Create AVDs
      - name: Create AVDs
        run: |
          echo "Creating first AVD..."
          echo "no" | avdmanager create avd -n emulator1 -k "system-images;android-29;default;x86_64" --force --abi default/x86_64 --sdcard 512M
          echo "Creating second AVD..."
          echo "no" | avdmanager create avd -n emulator2 -k "system-images;android-29;default;x86_64" --force --abi default/x86_64 --sdcard 512M
      
      # Step 11: Start both emulators in parallel and wait for them to be ready
      - name: Start Emulators
        run: |
            echo "Starting first emulator..."
            emulator -avd emulator1 -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim &
            echo "Starting second emulator..."
            emulator -avd emulator2 -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim &

            # Wait for both emulators to be ready before proceeding
            adb wait-for-device # Wait for the first device to be ready
            
            adb shell input keyevent 82 # Unlocks the first device

            adb wait-for-device # Wait for the second device to be ready
            
            adb shell input keyevent 82 # Unlocks the second device
            
            echo "Both emulators are ready."
            
            echo "Starting Appium Server..."
            appium & sleep 5
            
            echo "Running Tests on apk"
            mvn test

