name: Android CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13
    
    steps:
      # Step 1: Checkout the code from the repository
      - uses: actions/checkout@v4
      
      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      # Step 3: Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      # Step 4: Cache Maven packages to speed up builds
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
   
      # Step 5: Restart ADB Server
      - name: Restart ADB Server
        run: |
          adb kill-server || true # Ignore if ADB is not running
          adb start-server
            
      # Step 6: Create and start emulator
      - name: Create and start emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          force-avd-creation: true
          emulator-options: |
            -no-snapshot-save 
            -no-snapshot-load 
            -no-window 
            -gpu swiftshader_indirect 
            -noaudio 
            -no-boot-anim 
          disable-animations: true
          script: |
            echo "Emulator started - checking devices:"
            adb wait-for-device # Wait for device to be ready
            adb shell input keyevent 82 # Unlocks the device
      
      # Step 7: Start Appium server
      - name: Start Appium server
        run: |
          appium &
          sleep 5
      
      # Step 8: Build the project using Maven
      - name: Build with Maven
        run: mvn test -DsuiteXmlFile=AutoAssignRideFlow.xml

