name: Android CI with Maven
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Install Appium
        run: |
          npm i -g appium
          appium --version
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Restart ADB Server
        run: |
          adb kill-server || true # Ignore if ADB is not running
          adb start-server

      - name: Install Emulator and Required System Image
        run: |
          sdkmanager --install "emulator" "system-images;android-29;default;x86_64"
          sdkmanager --licenses

      - name: Create AVDs
        run: |
          echo "no" | avdmanager create avd -n emulator1 -k "system-images;android-29;default;x86_64" --force --device "pixel"
          echo "no" | avdmanager create avd -n emulator2 -k "system-images;android-29;default;x86_64" --force --device "pixel"

      - name: Start Two Emulators and Wait for Boot
        run: |
          echo "Starting first emulator..."
          nohup emulator -avd emulator1 -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim > /dev/null 2>&1 &

          echo "Starting second emulator..."
          nohup emulator -avd emulator2 -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim > /dev/null 2>&1 &

          echo "Waiting for both emulators to be ready..."
          for i in {1..30}; do
            if adb devices | grep -q "emulator-5554" && adb devices | grep -q "emulator-5556"; then
              echo "Both emulators are ready."
              break
            fi
            echo "Waiting for emulators to connect..."
            sleep 10
          done
          adb devices -l
          appium & sleep 5
          mvn test
