name: Android CI with Maven
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Install Appium
        run:  |
          npm i -g appium
          appium --version
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven- 
    
      - name: Restart ADB Server
        run: |
          adb kill-server || true # Ignore if ADB is not running
          adb start-server
          
      - name: Create and start emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          force-avd-creation: true
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: true
          script: |
            echo "Starting first emulator..."
            emulator -avd emulator1 -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim &
            echo "Starting second emulator..."
            emulator -avd emulator2 -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim &
            echo "Emulator started - checking devices:"
            adb devices
            echo " Both Emulators are ready"
            echo "Starting Appium Server....."
            appium & sleep 5
            echo "Running Tests on apk"
            mvn test
            
