name: Android CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13
    
    steps:
      # Step 1: Checkout the code from the repository
      - uses: actions/checkout@v4
      
      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      # Step 3: Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      # Step 4: Cache Maven packages to speed up builds
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      # Step 5: Restart ADB Server
      - name: Restart ADB Server
        run: |
          adb kill-server
          adb start-server

      # Step 6: Create and start the Android emulator
      - name: Create and start emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          force-avd-creation: true
          emulator-options: |
            -no-snapshot-save 
            -no-window 
            -gpu swiftshader_indirect 
            -noaudio 
            -no-boot-anim 
            -no-snapshot-load # Ensures cold boot every time
          disable-animations: true

      # Step 7: Wait for Emulator to be Ready and unlock it
      - name: Wait for Emulator to be Ready
        run: |
          adb wait-for-device # Wait for device to be ready
          adb shell input keyevent 82 # Unlocks the device

      # Step 8: Build the project using Maven
      - name: Build with Maven
        run: mvn clean package

